"""default model migration

Revision ID: 0824a9bb7af5
Revises: a60b58746657
Create Date: 2023-08-07 10:28:02.423334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0824a9bb7af5'
down_revision = 'a60b58746657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
