"""default model migration

Revision ID: 42eae1d6ccf4
Revises: 
Create Date: 2023-08-14 14:35:59.984362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42eae1d6ccf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('recipename', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('beef', 'pork', 'chicken', 'fish', 'vegetable', 'other'), nullable=False),
    sa.Column('photo', sa.Text(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipes_recipename'), 'recipes', ['recipename'], unique=False)
    op.create_table('recipeingredients',
    sa.Column('recipeingredient_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredientname', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('recipeingredient_id')
    )
    op.create_index(op.f('ix_recipeingredients_ingredientname'), 'recipeingredients', ['ingredientname'], unique=False)
    op.create_index(op.f('ix_recipeingredients_recipeingredient_id'), 'recipeingredients', ['recipeingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipeingredients_recipeingredient_id'), table_name='recipeingredients')
    op.drop_index(op.f('ix_recipeingredients_ingredientname'), table_name='recipeingredients')
    op.drop_table('recipeingredients')
    op.drop_index(op.f('ix_recipes_recipename'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
