"""default model migration

Revision ID: 4f8eedae3f8b
Revises: d1f528ea03b7
Create Date: 2023-08-05 23:43:01.742016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8eedae3f8b'
down_revision = 'd1f528ea03b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
