"""default model migration

Revision ID: 55f8319b80c9
Revises: bd5748507208
Create Date: 2023-08-07 10:43:11.827864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f8319b80c9'
down_revision = 'bd5748507208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
