"""default model migration

Revision ID: 6466ef84e4f3
Revises: fa0ff48e34e0
Create Date: 2023-08-05 14:23:21.737960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6466ef84e4f3'
down_revision = 'fa0ff48e34e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
