"""default model migration

Revision ID: 6db306d7c534
Revises: 0824a9bb7af5
Create Date: 2023-08-07 10:29:13.147680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db306d7c534'
down_revision = '0824a9bb7af5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
