"""default model migration

Revision ID: 9de75c128835
Revises: 55467f30b0a3
Create Date: 2023-08-05 13:36:44.719750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de75c128835'
down_revision = '55467f30b0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
