"""default model migration

Revision ID: a60b58746657
Revises: 4f8eedae3f8b
Create Date: 2023-08-07 09:06:46.796614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60b58746657'
down_revision = '4f8eedae3f8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
