"""default model migration

Revision ID: c71d5b13008d
Revises: f973515b4e14
Create Date: 2023-08-05 16:46:07.165257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c71d5b13008d'
down_revision = 'f973515b4e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
