"""default model migration

Revision ID: d1f528ea03b7
Revises: c71d5b13008d
Create Date: 2023-08-05 16:49:05.171908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f528ea03b7'
down_revision = 'c71d5b13008d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
