"""default model migration

Revision ID: f973515b4e14
Revises: 6466ef84e4f3
Create Date: 2023-08-05 16:20:54.746506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f973515b4e14'
down_revision = '6466ef84e4f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
