"""default model migration

Revision ID: fa0ff48e34e0
Revises: 9de75c128835
Create Date: 2023-08-05 13:39:49.366225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0ff48e34e0'
down_revision = '9de75c128835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
